name: Optimize Images

on:
  push:
    paths:
      - 'public/original-images/**'
      - 'scripts/compress-images.js'

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install sharp

      - name: Ejecutar compresión de imágenes
        run: node scripts/compress-images.js

      - name: Commit automático
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '♻️ Imágenes optimizadas automáticamente'
